language: go
sudo: false
go:
- 1.11.x
services:
  - postgresql
addons:
  postgresql: "9.4"
env:
  global:
    - GO111MODULE=on
    - QILINAPI_DATABASE_DSL=postgres://travistest:travistest@localhost:5432/qilin?sslmode=disable
    - QILINAPI_DATABASE_DEBUG=true
    - QILINAPI_JWT_SECRET=hlF0swObPsKN+0n3FVZd9ocfhjOmcS9A8QB7aZK5cDLPmK/QSXvksgkuBTErPfMEIPBKUtD28QjQqBVD9t/nVJ92qr1tlYq7e6F+mN/lYWNYdAApbR50BNY2+GPm/Tv8w1fwaMu7z08OU0+KBxHFxq+TbRusgOeeggovS4BnQ1FhoZv5So+Tf+bSCPQcWcbdPnw4IoM055qoFwvCz4AFi5ty7eCc1GvMVqU+6N/pPA4Q1LpB9+mG8rYbwoTuy31MF6lbhKlxRHRBUdkiJRhyeRskFI6neJ0rhNd62QzU82tyyYMKZ/s4/tBTk/YxvF7QP8cWBe9/kWu/DmUdecFq6w==
    - QILINAPI_JWT_ALGORITHM=HS256

install: true

before_script:
  - psql -c 'create database qilin;' -U postgres
  - psql -c "CREATE USER travistest WITH PASSWORD 'travistest';" -U postgres
  - psql -c "ALTER USER travistest WITH SUPERUSER;" -U postgres
  - psql -d qilin -c "CREATE EXTENSION pgcrypto;" -U postgres

script:
- go test ./... -coverprofile=coverage.out -covermode=atomic -p=1

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: mjcNZ8eKVqsDMfv61Et5QJ59mTOCJuZqVUwAM9eBrK8YAPOPiAifV+tIynp9wtGzNbmz7oMNGmHYdYwvnaiu7uoSLdjb7NInIsAsK+qvXDdJ9ebO/O9z3RSTuRzlM/uzvRtZ9I1w4wdzDxFp/5MhFH/eQPC5GN23o8lw2Z2VuTozztFM8S6DkH2WNYZFNzr/X60ol3GDs93fH8Lg7fVHRKdYgfmSao1aACd/+U9LG4te6D/XdVGNm9X6as9WTu4RafxHOoTSKYsLmLuUxVgvd0Ao8tp7Z78UsJqPvWG2yor6tnpMiFIQRYDP6Crg3rWTUM3mpswfj/oMAFBw0mc4qDN6Uni+IG9XfiI6u7mwHmKFo3YcuZ8APhJAaTRyII7QPkZw6DV0bOVK8c7taNpkQX/pU/vPQAawXng1/ZtZW83V/bsH2wG+R6IPl0mmExhIMFl62hHP2uxIJmgdSvx8Neuvh+P3mMRGe3o6fOC3PomBjxDqJKxbKS6JJ+8v1oZHZQUhkb09TeRMcwVU1+OPyHCqn2UHZEbsQsegSIMpjDTWFkUex+4TwSe1l7V4vSL1VWkl54VwQNh5SZViNTno7oKkJ0GchCtmbD+zpYxBdPzoAJtWcvWrG6S712C7WvBoMrAmXB64dQjeHjaaAu0qM65HFCxMofwrarcHpKP92W4=
