language: go
sudo: false
go:
- 1.11.x
services:
  - postgresql
env:
- GO111MODULE=on
install: true

before_script:
  - psql -c 'create database qilin;' -U postgres
  - psql -c "ALTER USER CURRENT_USER WITH PASSWORD 'travis'" -U travis;
  - sed -i -e 's/postgres/travis/g' ./etc/config.yaml

script:
- go test ./... -coverprofile=coverage.out -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack:
    secure: mjcNZ8eKVqsDMfv61Et5QJ59mTOCJuZqVUwAM9eBrK8YAPOPiAifV+tIynp9wtGzNbmz7oMNGmHYdYwvnaiu7uoSLdjb7NInIsAsK+qvXDdJ9ebO/O9z3RSTuRzlM/uzvRtZ9I1w4wdzDxFp/5MhFH/eQPC5GN23o8lw2Z2VuTozztFM8S6DkH2WNYZFNzr/X60ol3GDs93fH8Lg7fVHRKdYgfmSao1aACd/+U9LG4te6D/XdVGNm9X6as9WTu4RafxHOoTSKYsLmLuUxVgvd0Ao8tp7Z78UsJqPvWG2yor6tnpMiFIQRYDP6Crg3rWTUM3mpswfj/oMAFBw0mc4qDN6Uni+IG9XfiI6u7mwHmKFo3YcuZ8APhJAaTRyII7QPkZw6DV0bOVK8c7taNpkQX/pU/vPQAawXng1/ZtZW83V/bsH2wG+R6IPl0mmExhIMFl62hHP2uxIJmgdSvx8Neuvh+P3mMRGe3o6fOC3PomBjxDqJKxbKS6JJ+8v1oZHZQUhkb09TeRMcwVU1+OPyHCqn2UHZEbsQsegSIMpjDTWFkUex+4TwSe1l7V4vSL1VWkl54VwQNh5SZViNTno7oKkJ0GchCtmbD+zpYxBdPzoAJtWcvWrG6S712C7WvBoMrAmXB64dQjeHjaaAu0qM65HFCxMofwrarcHpKP92W4=
