Server:
  Port: 3001
Database:
  Host: localhost
  Port: 5432
  Database: qilin
  User: postgres
  Password:
Jwt:
  SignatureSecret:
  SignatureSecretBase64:
  Algorithm: "RS256"
GeoIP:
  DBPath:
LogConfig:
  Level: "debug"
  ReportCaller: true


