version: "3.6"

services:
  postgres9:
    image: postgres:9.4
    container_name: postgres9
    restart: always
    hostname: "postgres9"
    ports:
      - "5432:5432"
    volumes:
      - ./etc/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "4050:80"
    depends_on:
      - "postgres9"
    environment:
      PGADMIN_DEFAULT_EMAIL: maksim.blinenkov@protocol.one
      PGADMIN_DEFAULT_PASSWORD: 123
    logging:
      driver: none

  qilin-api:
    image: golang:1.11.5-stretch
    volumes:
      - .:/go/src/qilin-api
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /go/src/qilin-api
    command: go run main.go
    links:
      - postgres9
    environment:
      - GO111MODULE=on
      - QILINAPI_DATABASE_DSN=postgres://postgres:postgres@postgres9:5432/qilin?sslmode=disable
      - QILINAPI_DATABASE_DEBUG=true
      - QILINAPI_JWT_SECRET=hlF0swObPsKN+0n3FVZd9ocfhjOmcS9A8QB7aZK5cDLPmK/QSXvksgkuBTErPfMEIPBKUtD28QjQqBVD9t/nVJ92qr1tlYq7e6F+mN/lYWNYdAApbR50BNY2+GPm/Tv8w1fwaMu7z08OU0+KBxHFxq+TbRusgOeeggovS4BnQ1FhoZv5So+Tf+bSCPQcWcbdPnw4IoM055qoFwvCz4AFi5ty7eCc1GvMVqU+6N/pPA4Q1LpB9+mG8rYbwoTuy31MF6lbhKlxRHRBUdkiJRhyeRskFI6neJ0rhNd62QzU82tyyYMKZ/s4/tBTk/YxvF7QP8cWBe9/kWu/DmUdecFq6w==
      - QILINAPI_JWT_ALGORITHM=HS256