version: "3.6"

services:
  mongo:
    image: mongo:4.1.3
    container_name: mongo
    restart: always
    networks:
      - p1devnet
    volumes:
      - mongo:/var/lib/mongodb
    ports:
      - "3010:27017"

  postgres9:
    image: postgres:9.4
    container_name: postgres9
    restart: always
    hostname: "postgres9"
    networks:
      - p1devnet
    ports:
      - "5440:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    networks:
      - p1devnet
    ports:
      - "4050:80"
    depends_on:
      - "postgres9"
    environment:
      PGADMIN_DEFAULT_EMAIL: maksim.blinenkov@protocol.one
      PGADMIN_DEFAULT_PASSWORD: 123
    logging:
      driver: none

volumes:
  data:
    external: true
  mongo:
    external: true

networks:
  p1devnet:
    external: true