version: "3.6"

services:
  qilinapi-postgres:
    image: postgres:10.5
    container_name: qilinapi-postgres
    restart: unless-stopped
    networks: 
    - p1devnet
    ports:
      - "5432:5432"
    volumes:
      - ./etc/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      POSTGRES_PASSWORD: postgres

  qilinapi-pgadmin4:
    image: dpage/pgadmin4
    container_name: qilinapi-pgadmin4
    restart: unless-stopped
    networks: 
    - p1devnet
    ports:
      - "4050:80"
    depends_on:
      - qilinapi-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@test.local
      PGADMIN_DEFAULT_PASSWORD: 123
    logging:
      driver: none

  qilinapi:
    container_name: qilinapi
    image: golang:1.11.5-stretch
    depends_on:
      - qilinapi-postgres
    ports:
      - "3001:3001"
    networks: 
    - p1devnet
    volumes:
      - .:/go/src/qilin-api
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /go/src/qilin-api
    command: go run main.go
    environment:
      - GO111MODULE=on
      - QILINAPI_SERVER_PORT=3001
      - QILINAPI_SERVER_ALLOW_ORIGINS=http://localhost:8080
      - QILINAPI_SERVER_DEBUG=true
      - QILINAPI_SERVER_ALLOW_CREDENTIALS=true
      - QILINAPI_DATABASE_DSN=postgres://postgres:postgres@qilinapi-postgres:5432/qilin?sslmode=disable
      - QILINAPI_DATABASE_DEBUG=true
      - QILINAPI_JWT_SECRET=hlF0swObPsKN+0n3FVZd9ocfhjOmcS9A8QB7aZK5cDLPmK/QSXvksgkuBTErPfMEIPBKUtD28QjQqBVD9t/nVJ92qr1tlYq7e6F+mN/lYWNYdAApbR50BNY2+GPm/Tv8w1fwaMu7z08OU0+KBxHFxq+TbRusgOeeggovS4BnQ1FhoZv5So+Tf+bSCPQcWcbdPnw4IoM055qoFwvCz4AFi5ty7eCc1GvMVqU+6N/pPA4Q1LpB9+mG8rYbwoTuy31MF6lbhKlxRHRBUdkiJRhyeRskFI6neJ0rhNd62QzU82tyyYMKZ/s4/tBTk/YxvF7QP8cWBe9/kWu/DmUdecFq6w==
      - QILINAPI_JWT_ALGORITHM=HS256
      - QILINAPI_LOG_LEVEL=debug

networks:
  p1devnet:
    external: true      