version: "3.6"

services:
  qilin-api-go:
    build: .
    container_name: qilin-api-go
    networks:
      - p1devnet
    restart: always
    depends_on:
      - qilin-api-mongo
    ports:
      - "3001:3001"
    tty: true
    environment:
      QILIN_HOST: p1pay-api-mongo
      QILIN_DATABASE: p1pay_api
      QILIN_USER: ""
      QILIN_PASSWORD: ""

  qilin-api-nginx:
    image: nginx:latest
    container_name: qilin-api-nginx
    networks:
      - p1devnet
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - qilin-api-go

  qilin-api-mongo:
    image: mongo:4.1.3
    container_name: qilin-api-mongo
    restart: always
    networks:
      - p1devnet
    volumes:
      - qilin-api-mongo:/data/db
    ports:
      - "3002:27017"

volumes:
  qilin-api-mongo:
    external: true

networks:
  p1devnet:
    external: true