// Code generated by protoc-gen-go. DO NOT EDIT.
// source: packages_service.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscountOption int32

const (
	DiscountOption_WHOLE DiscountOption = 0
	DiscountOption_PART  DiscountOption = 1
)

var DiscountOption_name = map[int32]string{
	0: "WHOLE",
	1: "PART",
}

var DiscountOption_value = map[string]int32{
	"WHOLE": 0,
	"PART":  1,
}

func (x DiscountOption) String() string {
	return proto.EnumName(DiscountOption_name, int32(x))
}

func (DiscountOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{0}
}

type GetPackagePriceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=Country,proto3" json:"Country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPackagePriceRequest) Reset()         { *m = GetPackagePriceRequest{} }
func (m *GetPackagePriceRequest) String() string { return proto.CompactTextString(m) }
func (*GetPackagePriceRequest) ProtoMessage()    {}
func (*GetPackagePriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{0}
}

func (m *GetPackagePriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackagePriceRequest.Unmarshal(m, b)
}
func (m *GetPackagePriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackagePriceRequest.Marshal(b, m, deterministic)
}
func (m *GetPackagePriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackagePriceRequest.Merge(m, src)
}
func (m *GetPackagePriceRequest) XXX_Size() int {
	return xxx_messageInfo_GetPackagePriceRequest.Size(m)
}
func (m *GetPackagePriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackagePriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackagePriceRequest proto.InternalMessageInfo

func (m *GetPackagePriceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPackagePriceRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type GetPackagePriceResponse struct {
	Price                *Price   `protobuf:"bytes,1,opt,name=Price,proto3" json:"Price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPackagePriceResponse) Reset()         { *m = GetPackagePriceResponse{} }
func (m *GetPackagePriceResponse) String() string { return proto.CompactTextString(m) }
func (*GetPackagePriceResponse) ProtoMessage()    {}
func (*GetPackagePriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{1}
}

func (m *GetPackagePriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackagePriceResponse.Unmarshal(m, b)
}
func (m *GetPackagePriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackagePriceResponse.Marshal(b, m, deterministic)
}
func (m *GetPackagePriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackagePriceResponse.Merge(m, src)
}
func (m *GetPackagePriceResponse) XXX_Size() int {
	return xxx_messageInfo_GetPackagePriceResponse.Size(m)
}
func (m *GetPackagePriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackagePriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackagePriceResponse proto.InternalMessageInfo

func (m *GetPackagePriceResponse) GetPrice() *Price {
	if m != nil {
		return m.Price
	}
	return nil
}

type Price struct {
	Currency             string   `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Value                float32  `protobuf:"fixed32,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{2}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Price) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GetPackageRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPackageRequest) Reset()         { *m = GetPackageRequest{} }
func (m *GetPackageRequest) String() string { return proto.CompactTextString(m) }
func (*GetPackageRequest) ProtoMessage()    {}
func (*GetPackageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{3}
}

func (m *GetPackageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackageRequest.Unmarshal(m, b)
}
func (m *GetPackageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackageRequest.Marshal(b, m, deterministic)
}
func (m *GetPackageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackageRequest.Merge(m, src)
}
func (m *GetPackageRequest) XXX_Size() int {
	return xxx_messageInfo_GetPackageRequest.Size(m)
}
func (m *GetPackageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackageRequest proto.InternalMessageInfo

func (m *GetPackageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPackageResponse struct {
	Package              *Package `protobuf:"bytes,1,opt,name=Package,proto3" json:"Package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPackageResponse) Reset()         { *m = GetPackageResponse{} }
func (m *GetPackageResponse) String() string { return proto.CompactTextString(m) }
func (*GetPackageResponse) ProtoMessage()    {}
func (*GetPackageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{4}
}

func (m *GetPackageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPackageResponse.Unmarshal(m, b)
}
func (m *GetPackageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPackageResponse.Marshal(b, m, deterministic)
}
func (m *GetPackageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPackageResponse.Merge(m, src)
}
func (m *GetPackageResponse) XXX_Size() int {
	return xxx_messageInfo_GetPackageResponse.Size(m)
}
func (m *GetPackageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPackageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPackageResponse proto.InternalMessageInfo

func (m *GetPackageResponse) GetPackage() *Package {
	if m != nil {
		return m.Package
	}
	return nil
}

type PublishRequest struct {
	Package              *Package `protobuf:"bytes,1,opt,name=Package,proto3" json:"Package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{5}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetPackage() *Package {
	if m != nil {
		return m.Package
	}
	return nil
}

type PublishResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{6}
}

func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (m *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(m, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

type Package struct {
	Id                   string           `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Sku                  string           `protobuf:"bytes,2,opt,name=Sku,proto3" json:"Sku,omitempty"`
	Name                 *LocalizedString `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Image                *LocalizedString `protobuf:"bytes,4,opt,name=Image,proto3" json:"Image,omitempty"`
	ImageCover           *LocalizedString `protobuf:"bytes,5,opt,name=ImageCover,proto3" json:"ImageCover,omitempty"`
	ImageThumb           *LocalizedString `protobuf:"bytes,6,opt,name=ImageThumb,proto3" json:"ImageThumb,omitempty"`
	IsUpgradeAllowed     bool             `protobuf:"varint,7,opt,name=IsUpgradeAllowed,proto3" json:"IsUpgradeAllowed,omitempty"`
	IsEnabled            bool             `protobuf:"varint,8,opt,name=IsEnabled,proto3" json:"IsEnabled,omitempty"`
	DefaultProductId     string           `protobuf:"bytes,9,opt,name=DefaultProductId,proto3" json:"DefaultProductId,omitempty"`
	VendorId             string           `protobuf:"bytes,10,opt,name=VendorId,proto3" json:"VendorId,omitempty"`
	CreatorId            string           `protobuf:"bytes,11,opt,name=CreatorId,proto3" json:"CreatorId,omitempty"`
	Discount             uint32           `protobuf:"varint,12,opt,name=Discount,proto3" json:"Discount,omitempty"`
	DiscountOption       DiscountOption   `protobuf:"varint,13,opt,name=DiscountOption,proto3,enum=proto.DiscountOption" json:"DiscountOption,omitempty"`
	AllowedCountries     []string         `protobuf:"bytes,14,rep,name=AllowedCountries,proto3" json:"AllowedCountries,omitempty"`
	Products             []*Product       `protobuf:"bytes,15,rep,name=Products,proto3" json:"Products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Package) Reset()         { *m = Package{} }
func (m *Package) String() string { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()    {}
func (*Package) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{7}
}

func (m *Package) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Package.Unmarshal(m, b)
}
func (m *Package) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Package.Marshal(b, m, deterministic)
}
func (m *Package) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Package.Merge(m, src)
}
func (m *Package) XXX_Size() int {
	return xxx_messageInfo_Package.Size(m)
}
func (m *Package) XXX_DiscardUnknown() {
	xxx_messageInfo_Package.DiscardUnknown(m)
}

var xxx_messageInfo_Package proto.InternalMessageInfo

func (m *Package) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Package) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Package) GetName() *LocalizedString {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Package) GetImage() *LocalizedString {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Package) GetImageCover() *LocalizedString {
	if m != nil {
		return m.ImageCover
	}
	return nil
}

func (m *Package) GetImageThumb() *LocalizedString {
	if m != nil {
		return m.ImageThumb
	}
	return nil
}

func (m *Package) GetIsUpgradeAllowed() bool {
	if m != nil {
		return m.IsUpgradeAllowed
	}
	return false
}

func (m *Package) GetIsEnabled() bool {
	if m != nil {
		return m.IsEnabled
	}
	return false
}

func (m *Package) GetDefaultProductId() string {
	if m != nil {
		return m.DefaultProductId
	}
	return ""
}

func (m *Package) GetVendorId() string {
	if m != nil {
		return m.VendorId
	}
	return ""
}

func (m *Package) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *Package) GetDiscount() uint32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *Package) GetDiscountOption() DiscountOption {
	if m != nil {
		return m.DiscountOption
	}
	return DiscountOption_WHOLE
}

func (m *Package) GetAllowedCountries() []string {
	if m != nil {
		return m.AllowedCountries
	}
	return nil
}

func (m *Package) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{8}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type LocalizedStringArray struct {
	EN                   []string `protobuf:"bytes,1,rep,name=EN,proto3" json:"EN,omitempty"`
	RU                   []string `protobuf:"bytes,2,rep,name=RU,proto3" json:"RU,omitempty"`
	FR                   []string `protobuf:"bytes,3,rep,name=FR,proto3" json:"FR,omitempty"`
	ES                   []string `protobuf:"bytes,4,rep,name=ES,proto3" json:"ES,omitempty"`
	DE                   []string `protobuf:"bytes,5,rep,name=DE,proto3" json:"DE,omitempty"`
	IT                   []string `protobuf:"bytes,6,rep,name=IT,proto3" json:"IT,omitempty"`
	PT                   []string `protobuf:"bytes,7,rep,name=PT,proto3" json:"PT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalizedStringArray) Reset()         { *m = LocalizedStringArray{} }
func (m *LocalizedStringArray) String() string { return proto.CompactTextString(m) }
func (*LocalizedStringArray) ProtoMessage()    {}
func (*LocalizedStringArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{9}
}

func (m *LocalizedStringArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalizedStringArray.Unmarshal(m, b)
}
func (m *LocalizedStringArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalizedStringArray.Marshal(b, m, deterministic)
}
func (m *LocalizedStringArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalizedStringArray.Merge(m, src)
}
func (m *LocalizedStringArray) XXX_Size() int {
	return xxx_messageInfo_LocalizedStringArray.Size(m)
}
func (m *LocalizedStringArray) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalizedStringArray.DiscardUnknown(m)
}

var xxx_messageInfo_LocalizedStringArray proto.InternalMessageInfo

func (m *LocalizedStringArray) GetEN() []string {
	if m != nil {
		return m.EN
	}
	return nil
}

func (m *LocalizedStringArray) GetRU() []string {
	if m != nil {
		return m.RU
	}
	return nil
}

func (m *LocalizedStringArray) GetFR() []string {
	if m != nil {
		return m.FR
	}
	return nil
}

func (m *LocalizedStringArray) GetES() []string {
	if m != nil {
		return m.ES
	}
	return nil
}

func (m *LocalizedStringArray) GetDE() []string {
	if m != nil {
		return m.DE
	}
	return nil
}

func (m *LocalizedStringArray) GetIT() []string {
	if m != nil {
		return m.IT
	}
	return nil
}

func (m *LocalizedStringArray) GetPT() []string {
	if m != nil {
		return m.PT
	}
	return nil
}

type LocalizedString struct {
	EN                   string   `protobuf:"bytes,1,opt,name=EN,proto3" json:"EN,omitempty"`
	RU                   string   `protobuf:"bytes,2,opt,name=RU,proto3" json:"RU,omitempty"`
	FR                   string   `protobuf:"bytes,3,opt,name=FR,proto3" json:"FR,omitempty"`
	ES                   string   `protobuf:"bytes,4,opt,name=ES,proto3" json:"ES,omitempty"`
	DE                   string   `protobuf:"bytes,5,opt,name=DE,proto3" json:"DE,omitempty"`
	IT                   string   `protobuf:"bytes,6,opt,name=IT,proto3" json:"IT,omitempty"`
	PT                   string   `protobuf:"bytes,7,opt,name=PT,proto3" json:"PT,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocalizedString) Reset()         { *m = LocalizedString{} }
func (m *LocalizedString) String() string { return proto.CompactTextString(m) }
func (*LocalizedString) ProtoMessage()    {}
func (*LocalizedString) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1ea2e0463e18b5c, []int{10}
}

func (m *LocalizedString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocalizedString.Unmarshal(m, b)
}
func (m *LocalizedString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocalizedString.Marshal(b, m, deterministic)
}
func (m *LocalizedString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocalizedString.Merge(m, src)
}
func (m *LocalizedString) XXX_Size() int {
	return xxx_messageInfo_LocalizedString.Size(m)
}
func (m *LocalizedString) XXX_DiscardUnknown() {
	xxx_messageInfo_LocalizedString.DiscardUnknown(m)
}

var xxx_messageInfo_LocalizedString proto.InternalMessageInfo

func (m *LocalizedString) GetEN() string {
	if m != nil {
		return m.EN
	}
	return ""
}

func (m *LocalizedString) GetRU() string {
	if m != nil {
		return m.RU
	}
	return ""
}

func (m *LocalizedString) GetFR() string {
	if m != nil {
		return m.FR
	}
	return ""
}

func (m *LocalizedString) GetES() string {
	if m != nil {
		return m.ES
	}
	return ""
}

func (m *LocalizedString) GetDE() string {
	if m != nil {
		return m.DE
	}
	return ""
}

func (m *LocalizedString) GetIT() string {
	if m != nil {
		return m.IT
	}
	return ""
}

func (m *LocalizedString) GetPT() string {
	if m != nil {
		return m.PT
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.DiscountOption", DiscountOption_name, DiscountOption_value)
	proto.RegisterType((*GetPackagePriceRequest)(nil), "proto.GetPackagePriceRequest")
	proto.RegisterType((*GetPackagePriceResponse)(nil), "proto.GetPackagePriceResponse")
	proto.RegisterType((*Price)(nil), "proto.Price")
	proto.RegisterType((*GetPackageRequest)(nil), "proto.GetPackageRequest")
	proto.RegisterType((*GetPackageResponse)(nil), "proto.GetPackageResponse")
	proto.RegisterType((*PublishRequest)(nil), "proto.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "proto.PublishResponse")
	proto.RegisterType((*Package)(nil), "proto.Package")
	proto.RegisterType((*Product)(nil), "proto.Product")
	proto.RegisterType((*LocalizedStringArray)(nil), "proto.LocalizedStringArray")
	proto.RegisterType((*LocalizedString)(nil), "proto.LocalizedString")
}

func init() { proto.RegisterFile("packages_service.proto", fileDescriptor_c1ea2e0463e18b5c) }

var fileDescriptor_c1ea2e0463e18b5c = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x4f, 0xdb, 0x4a,
	0x10, 0x65, 0x93, 0x98, 0x24, 0x03, 0x98, 0xb0, 0xe2, 0xe6, 0xee, 0x8d, 0x6e, 0xab, 0xc8, 0x55,
	0xa5, 0x28, 0x6a, 0x79, 0xa0, 0x52, 0xa5, 0xa2, 0x52, 0x89, 0x26, 0x81, 0x5a, 0x45, 0x60, 0x39,
	0x86, 0x3e, 0x56, 0x8e, 0xbd, 0x05, 0x0b, 0x63, 0xa7, 0x6b, 0x9b, 0x2a, 0x7d, 0xeb, 0x4b, 0xff,
	0x62, 0xfb, 0x73, 0xaa, 0xfd, 0xb0, 0x09, 0x76, 0x41, 0x3c, 0x79, 0xcf, 0x99, 0x33, 0x3b, 0x67,
	0xd7, 0xb3, 0x03, 0xdd, 0xb9, 0xeb, 0x5d, 0xb9, 0x17, 0x34, 0xf9, 0x9c, 0x50, 0x76, 0x13, 0x78,
	0x74, 0x67, 0xce, 0xe2, 0x34, 0xc6, 0x9a, 0xf8, 0x18, 0xef, 0xa1, 0x7b, 0x44, 0x53, 0x4b, 0x6a,
	0x2c, 0x16, 0x78, 0xd4, 0xa6, 0x5f, 0x33, 0x9a, 0xa4, 0x58, 0x87, 0x9a, 0xe9, 0x13, 0xd4, 0x47,
	0x83, 0xb6, 0x5d, 0x33, 0x7d, 0x4c, 0xa0, 0x39, 0x8a, 0xb3, 0x28, 0x65, 0x0b, 0x52, 0x13, 0x64,
	0x0e, 0x8d, 0x7d, 0xf8, 0xb7, 0xb2, 0x47, 0x32, 0x8f, 0xa3, 0x84, 0x62, 0x03, 0x34, 0x41, 0x88,
	0x7d, 0xd6, 0x76, 0xd7, 0x65, 0xf1, 0x1d, 0x29, 0x92, 0x21, 0xe3, 0x8d, 0xd2, 0xe0, 0x1e, 0xb4,
	0x46, 0x19, 0x63, 0x34, 0xf2, 0x16, 0xaa, 0x6e, 0x81, 0xf1, 0x36, 0x68, 0xe7, 0x6e, 0x98, 0x51,
	0x51, 0xbb, 0x66, 0x4b, 0x60, 0x3c, 0x83, 0xad, 0xdb, 0xca, 0xf7, 0x18, 0x37, 0xde, 0x01, 0x5e,
	0x16, 0x29, 0x67, 0x03, 0x68, 0x2a, 0x4a, 0x79, 0xd3, 0x73, 0x6f, 0x4a, 0x98, 0x87, 0x8d, 0x3d,
	0xd0, 0xad, 0x6c, 0x16, 0x06, 0xc9, 0x65, 0x5e, 0xe1, 0xf1, 0xb9, 0x5b, 0xb0, 0x59, 0xe4, 0xca,
	0xc2, 0xc6, 0xef, 0x46, 0x91, 0x5d, 0xb9, 0xe3, 0x0e, 0xd4, 0xa7, 0x57, 0x99, 0xba, 0x5f, 0xbe,
	0xc4, 0x43, 0x68, 0x9c, 0xb8, 0xd7, 0x94, 0xd4, 0x45, 0x9d, 0xae, 0xaa, 0x73, 0x1c, 0x7b, 0x6e,
	0x18, 0x7c, 0xa7, 0xfe, 0x34, 0x65, 0x41, 0x74, 0x61, 0x0b, 0x0d, 0x7e, 0x01, 0x9a, 0x79, 0xcd,
	0x4d, 0x35, 0x1e, 0x14, 0x4b, 0x11, 0x7e, 0x0d, 0x20, 0x16, 0xa3, 0xf8, 0x86, 0x32, 0xa2, 0x3d,
	0x98, 0xb2, 0xa4, 0x2c, 0xf2, 0x9c, 0xcb, 0xec, 0x7a, 0x46, 0x56, 0x1f, 0x91, 0x27, 0x94, 0x78,
	0x08, 0x1d, 0x33, 0x39, 0x9b, 0x5f, 0x30, 0xd7, 0xa7, 0x07, 0x61, 0x18, 0x7f, 0xa3, 0x3e, 0x69,
	0xf6, 0xd1, 0xa0, 0x65, 0x57, 0x78, 0xfc, 0x3f, 0xb4, 0xcd, 0x64, 0x12, 0xb9, 0xb3, 0x90, 0xfa,
	0xa4, 0x25, 0x44, 0xb7, 0x04, 0xdf, 0x69, 0x4c, 0xbf, 0xb8, 0x59, 0x98, 0x5a, 0x2c, 0xf6, 0x33,
	0x2f, 0x35, 0x7d, 0xd2, 0x16, 0x57, 0x56, 0xe1, 0x79, 0x4f, 0x9d, 0xd3, 0xc8, 0x8f, 0x99, 0xe9,
	0x13, 0x90, 0x3d, 0x95, 0x63, 0x5e, 0x65, 0xc4, 0xa8, 0x9b, 0x8a, 0xe0, 0x9a, 0x08, 0xde, 0x12,
	0x3c, 0x73, 0x1c, 0x24, 0x1e, 0xef, 0x71, 0xb2, 0xde, 0x47, 0x83, 0x0d, 0xbb, 0xc0, 0x78, 0x1f,
	0xf4, 0x7c, 0x7d, 0x3a, 0x4f, 0x83, 0x38, 0x22, 0x1b, 0x7d, 0x34, 0xd0, 0x77, 0xff, 0x51, 0xf7,
	0x70, 0x37, 0x68, 0x97, 0xc4, 0xfc, 0x00, 0xea, 0xa4, 0xf2, 0x09, 0x05, 0x34, 0x21, 0x7a, 0xbf,
	0xce, 0x0f, 0x50, 0xe6, 0xf1, 0x10, 0x5a, 0xea, 0x34, 0x09, 0xd9, 0xec, 0xd7, 0x97, 0x9b, 0x4d,
	0xd2, 0x76, 0x11, 0x37, 0x5e, 0x42, 0x53, 0xad, 0x2b, 0x9d, 0x85, 0xa1, 0xe1, 0x2c, 0xe6, 0x54,
	0xb5, 0x96, 0x58, 0x1b, 0x3f, 0x11, 0x6c, 0x97, 0xfe, 0xd8, 0x01, 0x63, 0xee, 0x82, 0x27, 0x4f,
	0x4e, 0x08, 0x12, 0x8e, 0x6a, 0x93, 0x13, 0x8e, 0xed, 0x33, 0x52, 0x93, 0xd8, 0x3e, 0xe3, 0xf8,
	0xd0, 0x26, 0x75, 0x89, 0x0f, 0x6d, 0xa1, 0x9f, 0x92, 0x86, 0xd2, 0x4f, 0x39, 0x1e, 0x4f, 0x88,
	0x26, 0xf1, 0x78, 0x22, 0xcc, 0x38, 0x64, 0x55, 0x62, 0xd3, 0xe1, 0xd8, 0x72, 0x48, 0x53, 0x62,
	0xcb, 0x31, 0x7e, 0x20, 0xd8, 0x2c, 0x19, 0x29, 0x3c, 0xa0, 0x92, 0x07, 0x54, 0xf2, 0x80, 0x4a,
	0x1e, 0x50, 0xc9, 0x03, 0x2a, 0x79, 0x40, 0x25, 0x0f, 0x48, 0x7a, 0x18, 0x3e, 0x2f, 0xff, 0x52,
	0xdc, 0x06, 0xed, 0xd3, 0x87, 0xd3, 0xe3, 0x49, 0x67, 0x05, 0xb7, 0xa0, 0x61, 0x1d, 0xd8, 0x4e,
	0x07, 0xed, 0xfe, 0x42, 0xa0, 0xab, 0xd7, 0x3b, 0x95, 0xf3, 0x14, 0xef, 0x41, 0x53, 0xbd, 0x71,
	0x9c, 0xff, 0xff, 0xbb, 0xf3, 0xa2, 0xd7, 0x2d, 0xd3, 0x6a, 0x14, 0xac, 0xe0, 0xb7, 0x50, 0x3f,
	0xa2, 0x29, 0x26, 0x4a, 0x50, 0x19, 0x66, 0xbd, 0xff, 0xfe, 0x12, 0x29, 0xb2, 0x3f, 0x42, 0x8b,
	0xf3, 0x62, 0x78, 0x3e, 0xa9, 0x08, 0x97, 0xa7, 0x79, 0xef, 0xe9, 0x7d, 0xe1, 0x7c, 0xb3, 0xd9,
	0xaa, 0x10, 0xbc, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x92, 0xf9, 0xe4, 0x31, 0x06, 0x00,
	0x00,
}
