Server:
  Port: 3001
  AllowOrigins: ["http://localhost:8080"]
  AllowCredentials: true
Database:
  Host: localhost
  Port: 5440
  Database: qilin
  User: postgres
  Password:
Jwt:
  SignatureSecretBase64: "hlF0swObPsKN+0n3FVZd9ocfhjOmcS9A8QB7aZK5cDLPmK/QSXvksgkuBTErPfMEIPBKUtD28QjQqBVD9t/nVJ92qr1tlYq7e6F+mN/lYWNYdAApbR50BNY2+GPm/Tv8w1fwaMu7z08OU0+KBxHFxq+TbRusgOeeggovS4BnQ1FhoZv5So+Tf+bSCPQcWcbdPnw4IoM055qoFwvCz4AFi5ty7eCc1GvMVqU+6N/pPA4Q1LpB9+mG8rYbwoTuy31MF6lbhKlxRHRBUdkiJRhyeRskFI6neJ0rhNd62QzU82tyyYMKZ/s4/tBTk/YxvF7QP8cWBe9/kWu/DmUdecFq6w=="
  Algorithm: "HS256"
GeoIP:
  DBPath:
LogConfig:
  Level: "debug"
  ReportCaller: true
Email:
  Host: "localhost"
  Port: 25
  Username: "no-reply@protocol.one"
  Password: "123"