openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/protocolone6/Qilin/1.0.0
info:
  description: |
    # Introduction 

  version: "1.0.0a"
  title: Qilin API server
  contact:
    email: nikolay.bondarenko@protocol.one  
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /videogames/{id}:
    get:
      tags:
        - developers
      summary: Get video game object
      operationId: getGame
      description: |
        By passing in the appropriate options, you can grab all available 
        information abouth the game in the system
      parameters:
        - name: id
          in: path
          description: Game ID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoGame'
        '404':
          description: not found
