{{- $app := .Values.apps.p1payapi -}}
{{- $deployment := $app.deployments.nginx -}}
{{- $resourceName := printf "%s-%s" $app.name $deployment.name }}
{{- $appBackendName := printf "%s-%s" $app.name $app.deployments.gobackend.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $resourceName }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    app: {{ $app.name }}
    role: {{ $deployment.name }}
data:
  {{ $app.ingress.hostname }}.conf: |
      upstream {{ $appBackendName }}  {
        server {{ $appBackendName }}:{{ $app.deployments.gobackend.service.port }};
      }


      server {
        server_name {{ $app.ingress.hostname }};
        listen {{ $deployment.port }} default_server;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;

        location = /_healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }

        location / {
          proxy_pass http://{{ $appBackendName }};
        }
      }
