{{- $app := .Values.apps.p1payapi -}}
{{- if .Values.enableMongo }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $app.name }}-mongo
  labels:
    app: {{ $app.name }}
    role: mongo
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 172.29.13.72
    path: "/k8sdata/{{ $app.name }}-mongo"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $app.name }}-mongo
spec:
  storageClassName: ""
  selector:
    matchLabels:
      app: {{ $app.name }}
      role: mongo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}-mongo
  labels:
    app: {{ $app.name }}
    role: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
  selector:
    app: {{ $app.name }}
    role: mongo
---
apiVersion: apps/v1
#kind: StatefulSet
kind: Deployment
metadata:
  name: {{ $app.name }}-mongo
spec:
  selector:
    matchLabels:
      app: {{ $app.name }}
      role: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $app.name }}
        role: mongo
    spec:
      volumes:
      - name: {{ $app.name }}-mongo
        persistentVolumeClaim:
          claimName: {{ $app.name }}-mongo
      containers:
      - name: mongo
        image: library/mongo:4.1.3
        args: ["--auth"]
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: {{ $app.name }}-mongo
          mountPath: /data/db
          readOnly: false
{{- end }}