# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enableCertIssuer: true

ingress:
  hostname: qilinapi.tst.protocol.one
  path: /

certIssuer:
  email: admin@protocol.one

frontend:
  name: qilinapi
  role: frontend
  image: "p1hub/qilin.api"
  imageTag: latest
  port: 80
  replicas: 1
  service: 
    type: ClusterIP
    port: 80
    protocol: TCP
  env:
    - QILIN_API_SERVER_PORT
    - QILIN_API_SERVER_ALLOW_CREDENTIALS
    - QILIN_API_SERVER_DEBUG
    - QILIN_API_DATABASE_DSN
    - QILIN_API_DATABASE_DEBUG
    - QILIN_API_JWT_SECRET
    - QILIN_API_JWT_ALGORITHM
    - QILIN_API_LOG_LEVEL
    - QILIN_API_LOG_REPORT_CALLER
    - QILIN_API_MAILER_HOST
    - QILIN_API_MAILER_PORT
    - QILIN_API_MAILER_USERNAME
    - QILIN_API_MAILER_PASSWORD
    - QILIN_API_MAILER_REPLY_TO
    - QILIN_API_MAILER_FROM
    - QILIN_API_MAILER_SKIP_VERIFY

  
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
